//export const DOMAIN = 'localhost:3030/api/';
export const USER ='/api/user/';
export const LOGIN ='/api/auth/login/';
export const LOGOUT ='/api/auth/logout/';
export const REGISTER ='/api/auth/register/';
export const JOBS ='/jobs/';
export const COMPANIES ='/companies/';
export const GDID ='/companies/gdid/';
export const IPADDRESS = 'api.ipify.org/?format=json';
export const GLASSDOOR = 'api.glassdoor.com/api/api.htm';
export const GD_ID= "145422";
export const GD_KEY = "e0vj19EdTFo";
